# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'WaterLogging' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaterLogging
  pod 'MKRingProgressView'

  target 'WaterLoggingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
